### PR TITLE
create devnet specific endpoints

### PR DESCRIPTION
**Pull request by mubarak23**
## Checklist:

- [ ] API unification to follow JSON-RPC Spec #463 
- [ ]  Json-RPC call with both devnet prefix and non devnet prefix
- [ ] main the old setup while ensuring the added prefix work with route action

### CODE REVIEW

**Review by FabijanC — COMMENTED** [review]
If this PR is work in progress, please consider converting it to draft. Sorry to see that you didn't like the default PR checklist, it's very useful. Note that there are conflicts with `main` after #469.

**Comment by mubarak23** [comment]
> If this PR is work in progress, please consider converting it to draft. Sorry to see that you didn't like the default PR checklist, it's very useful. Note that there are conflicts with `main` after #469.

i will look into it and fix it

**Comment by mubarak23** [comment]
@FabijanC this is the PR, kindly review

**Review by FabijanC — CHANGES_REQUESTED** [review]
This is wrong. The idea is to make existing functionality (like minting) available via the `/rpc` endpoint, not introduce new endpoints. So, not to introduce `/devnet_mint`, but to have `/rpc` accept:
```
POST /rpc
{
  "method": "devnet_mint",
  ...
}
```

This is explained in #463

**Comment by mubarak23** [comment]
> This is wrong. The idea is to make existing functionality (like minting) available via the `/rpc` endpoint, not introduce new endpoints. So, not to introduce `/devnet_mint`, but to have `/rpc` accept:
> 
> ```
> POST /rpc
> {
>   "method": "devnet_mint",
>   ...
> }
> ```
> 
> This is explained in #463

i see, i will change it

**Comment by FabijanC** [comment]
@mubarak23 Any progress? Or do you want to be unassigned?

**Pull request closed without merging**
