### PR TITLE
Fix markdownlint of README

### PR DESCRIPTION
**Pull request by ClementWalter**
## Usage related changes

No usage changes

## Development related changes

No dev changes

## Checklist

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [x] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing - `cargo test`

### CODE REVIEW

**Review by mikiw — CHANGES_REQUESTED** [review]
Hi @ClementWalter. Is it possible to achieve the same results with a cargo package instead of npm? Also, this change should be applied in `scripts/format.sh`.

**Comment by taco-paco** [comment]
> Hi @ClementWalter. Is it possible to achieve the same results with a cargo package instead of npm? Also, formatting changes should be applied in `scripts/format.sh`.

Looks like its not possible right now. Bringing nodejs, npm to the project just for readme is too much I think.

As an alternative we can make CI action for this on merge action

**Comment by ClementWalter** [comment]
Actually I've discovered trunk.io today, and it's quite good, managing all the linter and their requiring deps under the hood. Just `trunk check` will check for any file types (most common), and I've even been able to add `cairo-format` in it.

Also comes with a github action and a nice VS Code plugin, very easy to set up

**Comment by taco-paco** [comment]
> Actually I've discovered trunk.io today, and it's quite good, managing all the linter and their requiring deps under the hood. Just `trunk check` will check for any file types (most common), and I've even been able to add `cairo-format` in it.
> 
> Also comes with a github action and a nice VS Code plugin, very easy to set up

Will have to take a look on that. If we find it suitable will you be interested on taking this task and do it in the following pr? If not we can remove `.prettierrs.json` from this pr and just merge README.md changes and create an `improvement` issue that we can take once more important features are done

**Comment by ClementWalter** [comment]
ok I can update this PR to use trunk

**Comment by FabijanC** [comment]
Closing as stale.

**Pull request closed without merging**
