### PR TITLE
Issue 387, Set gas price

### LINKED ISSUE #387: Set gas price
Its not possible to set the price in WEI and FRI for gas_price and data_gas_price.
At this stage the gas_price value is set for eth_l1_gas_price and strk_l1_gas_price.

Introduce new cli parameters specifying the Wei_gas_price, strk_gas_price, Wei_data_gas_price, strk_data_gas_price.
Then use those new parameters in init_block_context

### PR DESCRIPTION
**Pull request by Hueber9500**
## Usage related changes

closes #387 

## Checklist:

- [ ] Checked the relevant parts of [development docs](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#development)
- [ ] Applied formatting - `./scripts/format.sh`
- [ ] No linter errors - `./scripts/clippy_check.sh`
- [ ] No unused dependencies - `./scripts/check_unused_deps.sh`
- [ ] No spelling errors - `./scripts/check_spelling.sh`
- [ ] Performed code self-review
- [ ] Rebased to the latest commit of the target branch (or merged it into my branch)
- [ ] Updated the docs if needed, including the [TODO section](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#todo-to-reach-feature-parity-with-the-pythonic-devnet)
- [ ] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) which this PR resolves
- [ ] Updated the tests if needed; all passing ([execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution))

### CODE REVIEW

**Comment by marioiordanov** [comment]
In the readme section there is an example of devnet configuration response. Please update it to reflect the changes

**Review by marioiordanov — COMMENTED** [review]
looks good, will run the CI

**Comment by marioiordanov** [comment]
There is an error from clippy. Just add clippy too_many_arguments

**Comment by Hueber9500** [comment]
I added it

**Comment by marioiordanov** [comment]
before each push, run the scripts: format.sh and clippy_check.sh

**Comment by Hueber9500** [comment]
Pushed new changes

**Review by marioiordanov — APPROVED** [review]

**Pull request merged**
