### PR TITLE
Central folder for test files

### PR DESCRIPTION
**Pull request by marioiordanov**
## Development related changes

- Moved all test files to test_data folder in the root of the project. Each crate has folder as soft link to the test_data in the root. Every project have access to the same files.
- Organised the test contracts in folder cairo0 and cairo 1

## Checklist:

- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] Performed code self-review
- [x] Rebased to the last commit of the target branch (or merged it into my branch)
- [x] Documented the changes
- [x] Linked the issues which this PR resolves
- [x] Updated the tests
- [x] All tests are passing - `cargo test`

### CODE REVIEW

**Review by taco-paco — CHANGES_REQUESTED** [review]
Highly against this, especially with symlink which is already hardocoding so our repo compiles without a lot of changes. Types crate shall not be aware of test data of starknet crate or starknet-server crate. It breaks modularity and responsibility of a crate.

**Comment by taco-paco** [comment]
> Highly against this, especially with symlink which is already hardocoding so our repo compiles without a lot of changes. Types crate shall not be aware of test data of starknet crate or starknet-server crate. It breaks modularity and responsibility of a crate.

If any test data to be reused by other create by higher crate necessary utilities can be created in child test modules.

**Review by FabijanC — COMMENTED** [review]
Just to say that the PR looks good in the sense that it seems to implement what it states in the description. But let's reach a conclusion on if we need this change. Personally I don't see the symlinks and a common separate directory a problem. Perhaps we can create a new crate for holding test data (and potentially put e2e tests there, too).

**Review by mikiw — COMMENTED** [review]
Because of symlink usage, it doesn't work on windows.

There is a possibility to create a script that converts Unix symlink to Windows symlink and runs it on build or other trigger but the question is it worth it? Maybe it's just easier to go with Edwin's approach now.

**Comment by marioiordanov** [comment]
Converting to draft, because symlinks doesn't work on Windows as @mikiw tested.
Will have to find another solution

**Pull request closed without merging**
