### PR TITLE
cairo lang errs

### PR DESCRIPTION
**Pull request by lordshashank**
## Usage related changes
improves error handling

## Development related changes
Resolves https://github.com/0xSpaceShard/starknet-devnet-rs/issues/198

## Checklist:

- [X] Checked the relevant parts of [development docs](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#development)
- [X] Applied formatting - `./scripts/format.sh`
- [X] No linter errors - `./scripts/clippy_check.sh`
- [X] No unused dependencies - `./scripts/check_unused_deps.sh`
- [X] Performed code self-review
- [X] Rebased to the latest commit of the target branch (or merged it into my branch)
- [ ] Updated the docs if needed, including the [TODO section](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#todo-to-reach-feature-parity-with-the-pythonic-devnet)
- [X] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) which this PR resolves
- [ ] Updated the tests if needed; all passing ([execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution))

### CODE REVIEW

**Comment by lordshashank** [comment]
@marioiordanov is this what you meant (I took sierra errors from cairo_lang_starknet_classes, as cairo_lang_starknet had just abi errors in it) ? I have also not removed the "reason" property, let me know if you want it removed.

**Comment by lordshashank** [comment]
did that as following 
```
    #[error(transparent)]
    SierraCompilationError(#[from] StarknetSierraCompilationError),
```

Now, I tried to use ```?``` to auto parse error [here](https://github.com/lordshashank/starknet-devnet-rs/blob/ee86824c90e0f071dba4ea356563fd7097e5a633/crates/starknet-devnet-types/src/rpc/contract_class.rs#L121) but its not working, should I use StarknetSierraCompilationError variants here?

**Comment by lordshashank** [comment]
@marioiordanov 
did that as following 
```
    #[error(transparent)]
    SierraCompilationError(#[from] StarknetSierraCompilationError),
```

Now, I tried to use ```?``` to auto parse error [here](https://github.com/lordshashank/starknet-devnet-rs/blob/ee86824c90e0f071dba4ea356563fd7097e5a633/crates/starknet-devnet-types/src/rpc/contract_class.rs#L121) but its not working, should I use StarknetSierraCompilationError variants here?

**Comment by marioiordanov** [comment]
@lordshashank take a look at other error variants that have the same structure

**Comment by lordshashank** [comment]
@marioiordanov , I  have looked into the other variants, thing is StarknetSierraCompilationError has many variants [here](https://github.com/starkware-libs/cairo/blob/de1d5b1a47864a67ac8e2432323944bccae5464c/crates/cairo-lang-starknet-classes/src/casm_contract_class.rs#L64), 
Would downcasting work [here](https://github.com/lordshashank/starknet-devnet-rs/blob/ee86824c90e0f071dba4ea356563fd7097e5a633/crates/starknet-devnet-types/src/rpc/contract_class.rs#L121) so as to get the variant automatically like this
```
                let casm_json = usc::compile_contract(serde_json::to_value(sierra_contract_class).map_err(
                    |err| Error::JsonError(JsonError::Custom { msg: err.to_string() }),
                )?).map_err(|err| {
                    let err_str = err.to_string();
                    if let Some(sierra_error) = err.downcast::<StarknetSierraCompilationError>().ok() {
                        Error::SierraCompilationError(sierra_error)
                    } else {
                        Error::UnexpectedError(err_str)
                    }
                })?;
 ```

or should I use some specific variant only?

**Comment by marioiordanov** [comment]
@lordshashank sorry about misleading you, just add a String to the SierraCompilationError variant and then create the variant like this: Error::SierraCompilationError(err_str)

**Comment by lordshashank** [comment]
@marioiordanov I don't understand, do you want StarknetSierraCompilationError Error derivation to be removed here and just make variant from string message, if thats the case, it is already like that in repo's current state, then what changes do we intend to do in the issue?

**Comment by marioiordanov** [comment]
I just saw that there are two SierraCompilationError variants in different crates. Replace usage of SierraCompilationError variant from starknet_devnet_core::errors::Error with TypesError(starknet_devnet_types::error::Error::SierraCompilationError). Then delete the variant from starknet_devnet_core

**Comment by lordshashank** [comment]
@marioiordanov did that, let me know if something else is to be done here.

**Comment by lordshashank** [comment]
@marioiordanov should we change issue description if this is all to be done?

**Comment by marioiordanov** [comment]
@lordshashank we will just make a comment. Have to run the CI to approve your PR

**Comment by lordshashank** [comment]
Ok let me know if CI fails.

**Review by marioiordanov — APPROVED** [review]

**Pull request merged**
