### PR TITLE
chore: update dummy values in generate_hash of StarknetBlock

### LINKED ISSUE #21: Block hash computation
Check the implementation of Madara project for computing the block hash.

### PR DESCRIPTION
**Pull request by princeibs**
## Development related changes
Closes #21 

## Checklist:

- [ ] Checked the relevant parts of [development docs](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#development)
- [ ] Applied formatting - `./scripts/format.sh`
- [ ] No linter errors - `./scripts/clippy_check.sh`
- [ ] No unused dependencies - `./scripts/check_unused_deps.sh`
- [ ] No spelling errors - `./scripts/check_spelling.sh`
- [ ] Performed code self-review
- [ ] Rebased to the latest commit of the target branch (or merged it into my branch)
- [ ] Updated the docs if needed, including the [TODO section](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#todo-to-reach-feature-parity-with-the-pythonic-devnet)
- [ ] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) which this PR resolves
- [ ] Updated the tests if needed; all passing ([execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution))

### CODE REVIEW

**Comment by princeibs** [comment]
@marioiordanov 
@ivpavici 

Please kindly review.

**Comment by princeibs** [comment]
@marioiordanov kindly let me know if I am missing anything please

**Comment by ivpavici** [comment]
@princeibs Mario asked did you take a look at the Madara implementation? We have not investigated and cannot give you much more details (if we did we could implement the feature ourselves)

**Comment by marioiordanov** [comment]
@princeibs if you think its ready for review. Please mark it

**Comment by marioiordanov** [comment]
@princeibs before marking it as ready for review, please execute some of the required steps in the Checklist section of the PR description. So I will be able to run the CI pipeline

**Pull request closed without merging**
