### PR TITLE
Fix RPC error on starknet_getBlockTransactionCount

### LINKED ISSUE #496: fix `get_block_txs_count` endpoint error code
**Describe the bug (observed vs expected behavior)**
https://github.com/starkware-libs/starknet-specs/blob/304b952121dafe47c013ed2c4c39bef4cf4c2823/api/starknet_api_openrpc.json#L559
should return BLOCK_NOT_FOUND, but returns NO_BLOCKS

https://github.com/0xSpaceShard/starknet-devnet-rs/blob/3ad81456092a2da939be1f590855cea2c18ce40c/crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs#L261

### PR DESCRIPTION
**Pull request by tonypony220**
## Usage related changes
resolves #496 

## Checklist:

- [x] Checked out the [contribution guidelines](CONTRIBUTING.md)
- [x] Applied formatting - `./scripts/format.sh`
- [x] No linter errors - `./scripts/clippy_check.sh`
- [x] No unused dependencies - `./scripts/check_unused_deps.sh`
- [x] No spelling errors - `./scripts/check_spelling.sh`
- [x] Performed code self-review
- [x] Rebased to the latest commit of the target branch (or merged it into my branch)
- [x] Updated the docs if needed - `./website/README.md`
- [x] Linked the [issues](https://github.com/0xSpaceShard/starknet-devnet-rs/issues) resolvable by this PR - [linking info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] Updated the tests if needed; all passing - [execution info](https://github.com/0xSpaceShard/starknet-devnet-rs/?tab=readme-ov-file#test-execution)

### CODE REVIEW

**Review by FabijanC — CHANGES_REQUESTED** [review]
There are unchecked checkboxes in the PR description. If your PR is not yet reviewable, convert it to draft. I agree that the change you made is needed, but the tests for sure need to be updated:
- If there were tests checking if `NoBlocks` is returned, they should be changed to checking `BlockNotFound` is returned)
- If there were no tests for this case, they need to be added.

**Comment by FabijanC** [comment]
@tonypony220 how is it going? should someone else take over?

**Comment by tonypony220** [comment]
@FabijanC in progress, are you in rush for resolving this?

**Comment by FabijanC** [comment]
> @FabijanC in progress, are you in rush for resolving this?

Ok! Not in a rush, just want to prevent this from becoming stale.

**Review by FabijanC — APPROVED** [review]

**Pull request merged**
