### PR TITLE
Update Devnet Logo aligned with Starknet new logo

### PR DESCRIPTION
**Pull request by leoyoung-69**
I have made a new logo of Starknet Devnet. The Starknet logo in the center is changed into the new one.

Thank you.

### CODE REVIEW

**Review by Hanae1963 — APPROVED** [review]

**Review by FabijanC — CHANGES_REQUESTED** [review]
This PR doesn't just change the logo, it also adds an unwanted background, as can be seen here:
https://media.discordapp.net/attachments/1178603291005947954/1224611637512638524/image.png?ex=661e1f76&is=660baa76&hm=b1a9ae7c636780cc07a19a9823543d9eb6c7e576da733701e968af0ac1a7c739&=&format=webp&quality=lossless&width=1282&height=623

**Comment by leoyoung-69** [comment]
> This PR doesn't just change the logo, it also adds an unwanted grey background, as can be seen here: https://media.discordapp.net/attachments/1178603291005947954/1224611637512638524/image.png?ex=661e1f76&is=660baa76&hm=b1a9ae7c636780cc07a19a9823543d9eb6c7e576da733701e968af0ac1a7c739&=&format=webp&quality=lossless&width=1282&height=623

Hey,

I think I have updated it [here](https://private-user-images.githubusercontent.com/21069052/318352360-08ba1821-b241-44ca-9d72-79905a5e7fe9.png) without grey background. I am going to modify the color later.

Thank you,

**Comment by leoyoung-69** [comment]
@FabijanC it shows no backgroun in [my forked repo](https://github.com/leoyoung-69/starknet-devnet-rs-logo). Is it right?

**Comment by leoyoung-69** [comment]
logo

I think I should upload the logo here.

**Comment by leoyoung-69** [comment]
There is another one modified the keyboard frame color into light orange to align with the new logo color.
logo2

**Review by FabijanC — APPROVED** [review]

**Pull request merged**
